name: Go Test
description: Run and upload tests
author: me
requirements:
  - go
configuration:
  properties: {}
  additionalProperties: false
# configuration:
#   properties: {}
  #   dir:
  #     type: string
  # additionalProperties: false

