# image: packages.buildkite.com/vkstrm-co/stuff/gotest:latest
steps:
  # - label: ":pipeline: Pipeline upload"
  #   command: buildkite-agent pipeline upload

  - label: Build
    command: go build main.go
    key: build
    plugins:
      - docker#v5.13.0:
          image: "golang:1.26-alpine"

  - label: ":golang: Lint"
    plugins:
      - golangci-lint#v1.0.0: ~

  # - label: Test
  #   command: go test ./...
  #   key: test
  # 
  - label: Test
    plugins:
      - docker#v5.13.0:
          image: "packages.buildkite.com/vkstrm-co/stuff/gotest:latest"
      - ./gotestplugin: ~
        # dir: "./..."

